/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuadrosRouteImport } from './routes/quadros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsFaixaRouteImport } from './routes/workshops.$faixa'

const QuadrosRoute = QuadrosRouteImport.update({
  id: '/quadros',
  path: '/quadros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsFaixaRoute = WorkshopsFaixaRouteImport.update({
  id: '/workshops/$faixa',
  path: '/workshops/$faixa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quadros': typeof QuadrosRoute
  '/workshops/$faixa': typeof WorkshopsFaixaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quadros': typeof QuadrosRoute
  '/workshops/$faixa': typeof WorkshopsFaixaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quadros': typeof QuadrosRoute
  '/workshops/$faixa': typeof WorkshopsFaixaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quadros' | '/workshops/$faixa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quadros' | '/workshops/$faixa'
  id: '__root__' | '/' | '/quadros' | '/workshops/$faixa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuadrosRoute: typeof QuadrosRoute
  WorkshopsFaixaRoute: typeof WorkshopsFaixaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quadros': {
      id: '/quadros'
      path: '/quadros'
      fullPath: '/quadros'
      preLoaderRoute: typeof QuadrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/$faixa': {
      id: '/workshops/$faixa'
      path: '/workshops/$faixa'
      fullPath: '/workshops/$faixa'
      preLoaderRoute: typeof WorkshopsFaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuadrosRoute: QuadrosRoute,
  WorkshopsFaixaRoute: WorkshopsFaixaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
